app:
  port: 8080
db:
  driver: "mysql"
  # host: "host.docker.internal"
  # host: "db"
  host: "localhost"
  port: 3306
  username: your db username
  # username: root
  # username: admin
  # password: admin
  password: "your password"
  database: atplabs